### ISSUE TITLE
[1pt] More verbose processing milestone logs

### ISSUE THREAD

**Issue by JamesColl-NOAA** [NOAA-OWP/ras2fim#22]
## Current behavior
Currently ras simply prints out a processing I/O and successful / progress bar messages.  Therefore, at the end you need to manually peel into the outputs to see if anything useful was generated.  Understandable, but a few helpers along the way would be nice.

## Expected behavior
Please feel free to add requests here, but for now I have:
- [x] After step 3: Number of features which conflate
- [x] After step 5: The number of FIM rasters generated
- [x] After step 7: the [mean of the mean of the cross section elevations](https://github.com/NOAA-OWP/ras2fim/wiki/Explanation-of-the-Base-Scripts---ras2fim#7---calculate-terrain-statistics)
