### ISSUE TITLE
[13pt] Write inundation.py for ras2rem

### ISSUE THREAD

**Issue by CarsonPruitt-NOAA** [NOAA-OWP/ras2fim#29]
We need a inundation.py similar to the one in inundation-mapping for HAND. You might consider naming it something different like ras_inundation.py or another name if can come up with something good.

### Tasks:

- [ ] Get an example final ras2rem output from Jim.
- [ ] [Optional] Start with inundation-mapping `inundation.py` as a template. You can also just start from scratch if that seems more logical.
- [ ] The inputs should be: ras2rem directory and a flow file.
    - [ ] The flow file should be the exact same format that we use in inundation-mapping - a CSV with columns 'feature_id' and 'discharge' that represent the NWM feature ID and the discharge in CMS, respectively.
- [ ] The outputs should also be similar to the inundation-mapping version. Most importantly, we need a binary raster that represents we/dry. Secondly, an option for creating depth rasters is also required.

**Comment by CarsonPruitt-NOAA** [comment]
Here's the location for the 50-year flow file:
`/data/inundation_review/inundation_nwm_recurr/nwm_recurr_flow_data/nwm21_17C_recurr_50_0_cms.csv`

**Comment by LauraKeys-NOAA** [comment]
The initial version of this inundation is complete, with most of the modifications made to the ras2rem script and its outputs.
To do:

- Improve how the catchment / COMIDs are assigned (use official NWM catchments instead of extent of depth grids generated from the first 5 steps of ras2fim, which extend a few cross-sections beyond the catchment boundaries)
- Compare HAND results to the HEC-based results
- Test over additional sets of models besides the Iowa Flood Center sample

**Comment by LauraKeys-NOAA** [comment]
- [x] Improve how the catchment / COMIDs are assigned - use official NWM catchments instead of extent of depth grids generated from the first 5 steps of ras2fim, which extend a few cross-sections beyond the catchment boundaries. This step was combined with the task of vectorizing the catchments.

- [x] Compare HAND results to the HEC-based results using same input streamflows

- [x] Test over additional sets of models besides the Iowa Flood Center sample -> will need to do this for a TX HUC that Jim is processing (likely 12090301)
